# Generated by Django 3.2.9 on 2021-11-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerpath', '0002_alter_register_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='UpdateTime',
            field=models.DateField(max_length=30),
        ),
    ]
