# Generated by Django 3.2.9 on 2021-11-22 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careerpath', '0003_alter_register_updatetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='UpdateTime',
        ),
    ]
