# Generated by Django 3.2.9 on 2021-11-22 17:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('careerpath', '0004_remove_register_updatetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='UpdateTime',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
