# Generated by Django 3.2.7 on 2021-12-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerpath', '0005_register_updatetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('branch', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('Mobileno', models.CharField(max_length=10)),
                ('msg', models.TextField()),
            ],
        ),
    ]
