# Generated by Django 3.2.7 on 2021-12-03 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careerpath', '0006_feedback'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='feedback',
            table='feedback',
        ),
    ]
